# Implementasi Naive Bayes Studi Kasus Peminjaman Uang  (Tugas 8)


1.   Baca data *credit score*
2.   Buat data tes & data latih.
3.   Implementasikan algoritma berikut untuk menentukan kelas dari sebuah data


> Gaussian Naive Bayes


> K - Nearest Neighbors


> Decision Tree


4.   Tampilkan *accuracy, precision, & recall* dari setiap algoritma

## Baca Data 



*   Baca data dengan *library pandas* *italicized text*
*   Data [Credit Score](https://raw.githubusercontent.com/MuhammadKurniaSani-me/credit_score/main/credit_score.csv)

*   Data [Hitung Manual](https://docs.google.com/spreadsheets/d/1Yz2evrqDKDqPaltk3VhEDbd8QkbkXZjE/edit?usp=sharing&ouid=104778244268493691619&rtpof=true&sd=true)

### Persiapan Lingkungan


*   Impor *pandas library*
*   Impor *numpy library*
*   Impor *train_test_split* dari *sklearn*
*   Impor *gaussian naive bayes* dari *sklearn*
*   Impor *library* tambahan yang dibutuhkan dari *sklearn*

In [3]:
### Data Wrangling 
import pandas as pd
import numpy as np
from collections import OrderedDict

### Modelling 
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score, f1_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import StackingClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

### Remove unnecessary warnings
import warnings
warnings.filterwarnings('ignore')

In [2]:
import warnings
warnings.filterwarnings('ignore', category=UserWarning, append=True)

In [1]:
# load data set
dataset_url = ('https://raw.githubusercontent.com/rahadis/datamining/main/train.csv')

In [4]:
df = pd.read_csv(dataset_url)
df.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
#check number of rows and columns in dataset
df.shape

(2000, 21)

In [6]:
# select the class feature
labels = df["price_range"]

In [7]:
labels

0       1
1       2
2       2
3       2
4       1
       ..
1995    0
1996    2
1997    3
1998    0
1999    3
Name: price_range, Length: 2000, dtype: int64

In [8]:
# create a dataframe with all training data except the target column
X = df.drop(columns=["price_range"])

# check that the target variable has been removed
X.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2   2         20       756  2549     9     7         19   
1        136        3   6        905      1988  2631    17     3          7   
2        145        5   6       1263      1716  2603    11     2          9   
3        131        6   9       1216      1786  2769    16     8         11   
4        141        2  14       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  
0        0             0     1  
1        1             1     0  
2        1             1     0  
3        1             0     0  
4        1             1     0

In [9]:
scaler = MinMaxScaler()

In [11]:
scaler.fit(df)

MinMaxScaler()

In [12]:
normalized_feature = scaler.transform(df)

In [13]:
normalized_feature_df = pd.DataFrame(normalized_feature)

In [14]:
normalized_feature_df

0    1     2    3         4    5         6         7         8   \
0     0.227789  0.0  0.68  0.0  0.052632  0.0  0.080645  0.555556  0.900000   
1     0.347361  1.0  0.00  1.0  0.000000  1.0  0.822581  0.666667  0.466667   
2     0.041416  1.0  0.00  1.0  0.105263  1.0  0.629032  0.888889  0.541667   
3     0.076152  1.0  0.80  0.0  0.000000  0.0  0.129032  0.777778  0.425000   
4     0.881764  1.0  0.28  0.0  0.684211  1.0  0.677419  0.555556  0.508333   
...        ...  ...   ...  ...       ...  ...       ...       ...       ...   
1995  0.195725  1.0  0.00  1.0  0.000000  1.0  0.000000  0.777778  0.216667   
1996  0.977956  1.0  0.84  1.0  0.000000  0.0  0.596774  0.111111  0.891667   
1997  0.941884  0.0  0.16  1.0  0.052632  1.0  0.548387  0.666667  0.233333   
1998  0.675351  0.0  0.16  0.0  0.210526  1.0  0.709677  0.000000  0.541667   
1999  0.006012  1.0  0.60  1.0  0.263158  1.0  0.693548  0.888889  0.733333   

            9   ...        11        12        13        14        15  \
0     0.142857  ...  0.010204  0.170895  0.612774  0.285714  0.388889   
1     0.285714  ...  0.461735  0.993324  0.634687  0.857143  0.166667   
2     0.571429  ...  0.644388  0.811749  0.627205  0.428571  0.111111   
3     0.714286  ...  0.620408  0.858478  0.671566  0.785714  0.444444   
4     0.142857  ...  0.616327  0.475300  0.308658  0.214286  0.111111   
...        ...  ...       ...       ...       ...       ...       ...   
1995  0.714286  ...  0.623469  0.927904  0.110102  0.571429  0.222222   
1996  0.428571  ...  0.466837  0.977971  0.474613  0.428571  0.555556   
1997  1.000000  ...  0.442857  0.755674  0.748530  0.285714  0.055556   
1998  0.571429  ...  0.171429  0.113485  0.163816  0.928571  0.555556   
1999  0.714286  ...  0.246429  0.169559  0.978888  1.000000  0.222222   

            16   17   18   19        20  
0     0.944444  0.0  0.0  1.0  0.333333  
1     0.277778  1.0  1.0  0.0  0.666667  
2     0.388889  1.0  1.0  0.0  0.666667  
3     0.500000  1.0  0.0  0.0  0.666667  
4     0.722222  1.0  1.0  0.0  0.333333  
...        ...  ...  ...  ...       ...  
1995  0.944444  1.0  1.0  0.0  0.000000  
1996  0.777778  1.0  1.0  1.0  0.666667  
1997  0.166667  1.0  1.0  0.0  1.000000  
1998  0.944444  1.0  1.0  1.0  0.000000  
1999  0.000000  1.0  1.0  1.0  1.000000  

[2000 rows x 21 columns]

In [15]:
X = X.join(normalized_feature_df)

In [16]:
X = X.join(labels)

In [17]:
X

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...        12        13        14        15  \
0       0.6        188        2  ...  0.170895  0.612774  0.285714  0.388889   
1       0.7        136        3  ...  0.993324  0.634687  0.857143  0.166667   
2       0.9        145        5  ...  0.811749  0.627205  0.428571  0.111111   
3       0.8        131        6  ...  0.858478  0.671566  0.785714  0.444444   
4       0.6        141        2  ...  0.475300  0.308658  0.214286  0.111111   
...     ...        ...      ...  ...       ...       ...       ...       ...   
1995    0.8        106        6  ...  0.927904  0.110102  0.571429  0.222222   
1996    0.2        187        4  ...  0.977971  0.474613  0.428571  0.555556   
1997    0.7        108        8  ...  0.755674  0.748530  0.285714  0.055556   
1998    0.1        145        5  ...  0.113485  0.163816  0.928571  0.555556   
1999    0.9        168        6  ...  0.169559  0.978888  1.000000  0.222222   

            16   17   18   19        20  price_range  
0     0.944444  0.0  0.0  1.0  0.333333            1  
1     0.277778  1.0  1.0  0.0  0.666667            2  
2     0.388889  1.0  1.0  0.0  0.666667            2  
3     0.500000  1.0  0.0  0.0  0.666667            2  
4     0.722222  1.0  1.0  0.0  0.333333            1  
...        ...  ...  ...  ...       ...          ...  
1995  0.944444  1.0  1.0  0.0  0.000000            0  
1996  0.777778  1.0  1.0  1.0  0.666667            2  
1997  0.166667  1.0  1.0  0.0  1.000000            3  
1998  0.944444  1.0  1.0  1.0  0.000000            0  
1999  0.000000  1.0  1.0  1.0  1.000000            3  

[2000 rows x 42 columns]

In [18]:
# percent_amount_of_test_data = / HUNDRED_PERCENT
percent_amount_of_test_data = 0.3

In [19]:
X.shape

(2000, 42)

In [20]:
X

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...        12        13        14        15  \
0       0.6        188        2  ...  0.170895  0.612774  0.285714  0.388889   
1       0.7        136        3  ...  0.993324  0.634687  0.857143  0.166667   
2       0.9        145        5  ...  0.811749  0.627205  0.428571  0.111111   
3       0.8        131        6  ...  0.858478  0.671566  0.785714  0.444444   
4       0.6        141        2  ...  0.475300  0.308658  0.214286  0.111111   
...     ...        ...      ...  ...       ...       ...       ...       ...   
1995    0.8        106        6  ...  0.927904  0.110102  0.571429  0.222222   
1996    0.2        187        4  ...  0.977971  0.474613  0.428571  0.555556   
1997    0.7        108        8  ...  0.755674  0.748530  0.285714  0.055556   
1998    0.1        145        5  ...  0.113485  0.163816  0.928571  0.555556   
1999    0.9        168        6  ...  0.169559  0.978888  1.000000  0.222222   

            16   17   18   19        20  price_range  
0     0.944444  0.0  0.0  1.0  0.333333            1  
1     0.277778  1.0  1.0  0.0  0.666667            2  
2     0.388889  1.0  1.0  0.0  0.666667            2  
3     0.500000  1.0  0.0  0.0  0.666667            2  
4     0.722222  1.0  1.0  0.0  0.333333            1  
...        ...  ...  ...  ...       ...          ...  
1995  0.944444  1.0  1.0  0.0  0.000000            0  
1996  0.777778  1.0  1.0  1.0  0.666667            2  
1997  0.166667  1.0  1.0  0.0  1.000000            3  
1998  0.944444  1.0  1.0  1.0  0.000000            0  
1999  0.000000  1.0  1.0  1.0  1.000000            3  

[2000 rows x 42 columns]

### Hitung Data

*   Pisahkan kolom "risk_rating" dari *dataframe*
*   Ambil kolom "risk_rating" sebagai target kolom untuk kategori kelas
*   Pisahkan data latih dengan data tes


```
# data latih (nilai data)
X_train 

# data tes (nilai data)
X_test 

# data latih (kelas data)
y_train

# data tes (kelas data)
y_test
```

In [21]:
# separate target 

# values
matrices_X = X.iloc[:,0:10].values

# classes
matrices_Y = X.iloc[:,10].values

In [22]:
X_1 = X.iloc[:,0:10].values
Y_1 = X.iloc[:, -1].values

In [23]:
# X_train, X_test, y_train, y_test = train_test_split(matrices_X, matrices_Y, test_size = percent_amount_of_test_data, random_state=0)
X_train, X_test, y_train, y_test = train_test_split(X_1, Y_1, test_size = percent_amount_of_test_data, random_state=0)

In [24]:
X_1

array([[8.420e+02, 0.000e+00, 2.200e+00, ..., 6.000e-01, 1.880e+02,
        2.000e+00],
       [1.021e+03, 1.000e+00, 5.000e-01, ..., 7.000e-01, 1.360e+02,
        3.000e+00],
       [5.630e+02, 1.000e+00, 5.000e-01, ..., 9.000e-01, 1.450e+02,
        5.000e+00],
       ...,
       [1.911e+03, 0.000e+00, 9.000e-01, ..., 7.000e-01, 1.080e+02,
        8.000e+00],
       [1.512e+03, 0.000e+00, 9.000e-01, ..., 1.000e-01, 1.450e+02,
        5.000e+00],
       [5.100e+02, 1.000e+00, 2.000e+00, ..., 9.000e-01, 1.680e+02,
        6.000e+00]])

In [25]:
Y_1

array([1, 2, 2, ..., 3, 0, 3])

In [26]:
### Dictionary to store model and its accuracy

model_accuracy = OrderedDict()

### Dictionary to store model and its precision

model_precision = OrderedDict()

### Dictionary to store model and its recall

model_recall = OrderedDict()

An example data to test from customer "Dio"


---


*    overdue 0 - 30  days : 0
*    overdue 31 - 45 days : 0
*    overdue 46 - 60 days : 0 
*    overdue 61 - 90 days : 0
*    overdue > 90 days    : 0 
*    KPR_TIDAK : 0
*    KPR_YA	: 1
*    norm_pendapatan_setahun_juta : 0.582609 
*    norm_durasi_pinjaman_bulan	: 0.666667  
*    norm_jumlah_tanggungan	: 0

Determine the risk_rating

```
# Data example 'Dio' customer
[0,	0,	0,	0,	0,	0,	1,	0.582609,	0.666667,	0]
```



#### Implementasi Gaussian Naive Bayes

In [27]:
### Applying Naive Bayes Classification model

naive_bayes_classifier = GaussianNB()
naive_bayes_classifier.fit(X_train, y_train)
Y_pred_nb = naive_bayes_classifier.predict(X_test)


### Making the confusion matrix
cm = confusion_matrix(y_test, Y_pred_nb)


### Printing the accuracy, precision, and recall of the model
print('Confusion matrix for Gaussian Naive Bayes\n',cm)

naive_bayes_accuracy = round(100 * accuracy_score(y_test, Y_pred_nb), 2)
model_accuracy['Gaussian Naive Bayes'] = naive_bayes_accuracy

naive_bayes_precision = round(100 * precision_score(y_test, Y_pred_nb, average = 'weighted'), 2)
model_precision['Gaussian Naive Bayes'] = naive_bayes_precision

naive_bayes_recall = round(100 * recall_score(y_test, Y_pred_nb, average = 'weighted'), 2)
model_recall['Gaussian Naive Bayes'] = naive_bayes_recall

print('The accuracy of this model is {} %.'.format(naive_bayes_accuracy))
print('The precision of this model is {} %.'.format(naive_bayes_precision))
print('The recall of this model is {} %.'.format(naive_bayes_recall))


Confusion matrix for Gaussian Naive Bayes
 [[65 28 23 35]
 [62 29 14 30]
 [55 26 29 41]
 [37 41 24 61]]
The accuracy of this model is 30.67 %.
The precision of this model is 30.76 %.
The recall of this model is 30.67 %.


In [28]:
clf = GaussianNB()
clf.fit(matrices_X, matrices_Y)
clf_pf = GaussianNB()
clf_pf.partial_fit(matrices_X, matrices_Y, np.unique(matrices_Y))

GaussianNB()

In [29]:
FIRST_IDX = 0

In [30]:
# try with value [0,	0,	0,	0,	0,	0,	1,	0.582609,	0.666667,	0]
result_test_naive_bayes = clf_pf.predict([[0,	0,	0,	0,	0,	0,	1,	0.582609,	0.666667,	0]])[FIRST_IDX]
print(f"Customer Name : Dio has risk rating {result_test_naive_bayes} based on Gaussian Naive Bayes model")

Customer Name : Dio has risk rating 1 based on Gaussian Naive Bayes model


#### Implementasi K - Nearest Neighbors



*   Tentukan nilai K = 10 (10 tetangga terdekat)
*   Buat data latih

In [31]:
amount_of_neighbor = 10

In [32]:
# Fit the classifier to the data
knn = KNeighborsClassifier(n_neighbors = amount_of_neighbor)

# create train data
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=10)

In [33]:
#show first 5 model predictions on the test data
Y_pred_knn = knn.predict(X_test)

In [34]:
#check accuracy of our model on the test data
knn.score(X_test, y_test)

0.29

In [35]:
# Custom value to predict
result_test_knn = knn.predict([[0,	0,	0,	0,	0,	0,	1,	0.582609,	0.666667,	0]])
print(f"Customer Name : Dio has risk rating {result_test_knn[FIRST_IDX]} based on KNN model")

Customer Name : Dio has risk rating 1 based on KNN model


In [ ]:
### Making the confusion matrix
cm = confusion_matrix(y_test, Y_pred_knn)

### Printing the accuracy, precision, and recall of the model
print('Confusion matrix for K - Nearest Neighbors\n',cm)
nn1_accuracy = round(100 * accuracy_score(y_test, Y_pred_knn), 2)
model_accuracy['1 - Nearest Neighbors'] = nn1_accuracy

nn1_precision = round(100 * precision_score(y_test, Y_pred_knn, average = 'weighted'), 2)
model_precision['1 - Nearest Neighbors'] = nn1_precision

nn1_recall = round(100 * recall_score(y_test, Y_pred_knn, average = 'weighted'), 2)
model_recall['1 - Nearest Neighbors'] = nn1_recall

print('The accuracy of this model is {} %.'.format(nn1_accuracy))
print('The precision of this model is {} %.'.format(nn1_precision))
print('The recall of this model is {} %.'.format(nn1_recall))

Confusion matrix for K - Nearest Neighbors
 [[69  0  0  0  0]
 [ 0 49  0  0  0]
 [ 0  1 83  0  0]
 [ 0  0  0 36  0]
 [ 0  1  0  0 31]]
The accuracy of this model is 99.26 %.
The precision of this model is 99.29 %.
The recall of this model is 99.26 %.


#### Implementasi Decision Tree

In [ ]:
### Applying Decision Tree Classification model

decision_tree_classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 27)
decision_tree_classifier.fit(X_train, y_train)


### Predicting the Test set results

Y_pred_dc = decision_tree_classifier.predict(X_test)

In [ ]:
### Making the confusion matrix
cm = confusion_matrix(y_test, Y_pred_dc)

### Printing the accuracy, precision, and recall of the model
print('Confusion matrix for Decision Tree\n',cm)

decision_tree_accuracy = round(100 * accuracy_score(y_test, Y_pred_dc), 2)
model_accuracy['Decision Tree'] = decision_tree_accuracy

decision_tree_precision = round(100 * precision_score(y_test, Y_pred_dc, average = 'weighted'), 2)
model_precision['Decision Tree'] = decision_tree_precision

decision_tree_recall = round(100 * recall_score(y_test, Y_pred_dc, average = 'weighted'), 2)
model_recall['Decision Tree'] = decision_tree_recall

print('The accuracy of this model is {} %.'.format(decision_tree_accuracy))
print('The precision of this model is {} %.'.format(decision_tree_precision))
print('The recall of this model is {} %.'.format(decision_tree_recall))

Confusion matrix for Decision Tree
 [[69  0  0  0  0]
 [ 0 49  0  0  0]
 [ 0  0 84  0  0]
 [ 0  0  0 36  0]
 [ 0  0  0  0 32]]
The accuracy of this model is 100.0 %.
The precision of this model is 100.0 %.
The recall of this model is 100.0 %.
